Models/CityWeather.cs
namespace WeatherAppAssignment.Models;

public class CityWeather
{
    public string CityUniqueCode { get; set; }
    public string CityName { get; set; }
    public DateTime DateAndTime { get; set; }
    public int TemperatureFahrenheit { get; set; }
}

Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using WeatherAppAssignment.Models;

namespace WeatherAppAssignment.Controllers;

public class WeatherController : Controller
{
    [Route("/")]
    public IActionResult Index()
    {
        List<CityWeather> weatherData = new List<CityWeather>()
        {
            new CityWeather {CityUniqueCode = "LDN", CityName = "London", DateAndTime = DateTime.Parse("2030-01-01 8:00"),  TemperatureFahrenheit = 33},
            new CityWeather {CityUniqueCode = "NYC", CityName = "London", DateAndTime = DateTime.Parse("2030-01-01 3:00"),  TemperatureFahrenheit = 60},
            new CityWeather {CityUniqueCode = "PAR", CityName = "Paris", DateAndTime = DateTime.Parse("2030-01-01 9:00"),  TemperatureFahrenheit = 82}
        };
        return View(weatherData);
    }

    [Route("/weather/{cityCode}")]
    public IActionResult ViewDetails(string? cityCode)
    {
        List<CityWeather> weatherData = new List<CityWeather>()
        {
            new CityWeather {CityUniqueCode = "LDN", CityName = "London", DateAndTime = DateTime.Parse("2030-01-01 8:00"),  TemperatureFahrenheit = 33},
            new CityWeather {CityUniqueCode = "NYC", CityName = "London", DateAndTime = DateTime.Parse("2030-01-01 3:00"),  TemperatureFahrenheit = 60},
            new CityWeather {CityUniqueCode = "PAR", CityName = "Paris", DateAndTime = DateTime.Parse("2030-01-01 9:00"),  TemperatureFahrenheit = 82}
        };

        CityWeather? mathchingCity = weatherData.Where(city => city.CityUniqueCode == cityCode).FirstOrDefault();

        return View(mathchingCity);
    }
}

ViewComponents/WeatherGridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WeatherAppAssignment.Models;

namespace WeatherAppAssignment.ViewComponents;

public class WeatherGridViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(CityWeather city)
    {
        ViewData["TemperatureFahrenheit"] = GetCssClassByFahrenheit(city.TemperatureFahrenheit);
        return View("Sample",city);
    }
    public string GetCssClassByFahrenheit(int temp){
        if (temp < 44)
        {
            return "blue-back";
        }
        else if (temp >= 44 && temp < 74)
        {
            return "green-back";
        }
        else
        {
            return "orange-back";
        }
    }
}

Views/Shared/Components/WeatherGrid/Sample.cshtml
@model CityWeather


<div class="box w-25 float-left @ViewData["TemperatureFahrenheit"]">
    <div class="float-left w-75">
        <h3>@Model.CityName</h3>
        <h4>@Model.DateAndTime.ToString("hh:mm tt")</h4>
        <a href="/weather/@Model.CityUniqueCode" class="details">Details</a>
    </div>
    <div class="">
        <h3>@Model.TemperatureFahrenheit <span class="">°F</span></h3>

    </div>
</div>

Views/Shared/_Layouts.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Weather App</title>
    <meta charset="utf-8" />
    <link href="~/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <h1>Weather</h1>
    <div class="page-content">
        @RenderBody()
    </div>
    
</body>
</html>

Views/Shared/_WeatherListPartialView.cshtml
@model IEnumerable<CityWeather>

@foreach (var weather in Model)
{
    <div class="box w-25 float-left @ViewBag.TemperatureFahrenheit">
        <div class="float-left w-75">
            <h3>@weather.CityName</h3>
            <h4>@weather.DateAndTime.ToString("hh:mm tt")</h4>
            <a href="/weather/@weather.CityUniqueCode" class="details">Details</a>
        </div>
        <div class="">
            <h3>@weather.TemperatureFahrenheit <span class="">°F</span></h3>

        </div>
    </div>
}

Views/Weather/Index.cshtml
@model IEnumerable<CityWeather>

@foreach(CityWeather city in Model)
{
    @await Component.InvokeAsync("WeatherGrid",new {
        city = city
    })
}

Views/Weather/ViewDetails.cshtml
@model CityWeather

<div class="box w-25 float-left">
    <div class="float-left w-75">
        <h3>@Model.CityName</h3>
        <h4>@Model.DateAndTime.ToString("hh:mm tt")</h4>
        <a href="/" class="details">Back to Weather Homepage</a>
    </div>
    <div class="">
        <h3>@Model.TemperatureFahrenheit <span class="">°F</span></h3>
    </div>
</div>